### ISSUE TITLE
CORS header 'Access-Control-Allow-Origin' missing

### ISSUE THREAD

**Issue by eddentsai** [binance/binance-connector-node#100]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
Briefly describe the issue here.
I write code as the following (with vuetify)
import { Spot } from "@binance/connector";
const apiKey = 'myapikey';
const apiSec = 'myapiSec';
const client = new Spot(apiKey,apiSec);
client.coinInfo().then((response) => console.log(response.data));

I always get  CORS header 'Access-Control-Allow-Origin' missing

### Expected behaviour
Describe what should happen.
print coin info list

### Actual behaviour
Describe what happens instead. Please include the complete failure message.
CORS header 'Access-Control-Allow-Origin' missing

### Steps to reproduce
Provide steps to let us know how we can reproduce this issue.
import { Spot } from "@binance/connector";
const apiKey = 'myapikey';
const apiSec = 'myapiSec';
const client = new Spot(apiKey,apiSec);
client.coinInfo().then((response) => console.log(response.data));

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-node 1.12.0
* Node version v16.13.2
* Operating system macbook m1
* package.json
{
  "name": "crypto-tools",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@binance/connector": "^1.12.0",
    "core-js": "^3.8.3",
    "crypto-js": "4.1.1",
    "node-polyfill-webpack-plugin": "^2.0.0",
    "vue": "^2.6.14",
    "vue-router": "^3.5.4",
    "vuetify": "^2.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/eslint-parser": "^7.12.16",
    "@babel/preset-env": "^7.18.9",
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
    "eslint": "^7.32.0",
    "eslint-plugin-vue": "^8.0.3",
    "sass": "~1.32.0",
    "sass-loader": "^10.0.0",
    "vue-cli-plugin-vuetify": "~2.5.1",
    "vue-template-compiler": "^2.6.14",
    "vuetify-loader": "^1.7.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "@babel/eslint-parser"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

**Comment by 2pd** [comment]
Do you have screenshot of the error?

**Comment by tantialex** [comment]
CORS requests are not supported for authorised endpoints.
