### ISSUE TITLE
I want to build a website like bingx.com or binance.com

### ISSUE THREAD

**Issue by Stevemoretz** [binance/binance-connector-node#118]
### Issue subject

Hi, can we use this package or in general the binance api to build pages that are available on the website, but on our own website?

eg I want to build this page: https://www.binance.com/en/trade/BTC_USDT?theme=light&type=spot
Trading View provides a chart library:
https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/?feature=charting-and-trading-platform

Did you use that? How can I build something like yours on my own website?

**Comment by 2pd** [comment]
Close this as it's not related to this library.
