### ISSUE TITLE
When working with a stream, the "close:" callback is not called

### ISSUE THREAD

**Issue by Blazheiko** [binance/binance-connector-node#126]
When working with a stream, the "close:" callback is not called.
`websocket.js.
 ws.on('close', (closeEventCode, reason) => {
        if (!wsRef.closeInitiated) {
          this.logger.error('Connection close due to ${closeEventCode}: ${reason}.')
          setTimeout(() => {
            this.logger.debug('Reconnect to the server.')
            initConnect()
          }, this.reconnectDelay)
        } else {
          wsRef.closeInitiated = false
        }
      }) `

**Comment by 2pd** [comment]
do you receive the close message? or do you have any log?

**Comment by Blazheiko** [comment]
I am not getting a closing message.In the websocket.js file in the subscribe method (url, callbacks) in the corresponding "close" event handler does not trigger the callback to report the "close" event to the top

**Comment by 2pd** [comment]
this has been fixed in the #129

**Comment by Blazheiko** [comment]
Thank you
