### ISSUE TITLE
Binance websocket testnet connection disconnecting

### ISSUE THREAD

**Issue by prasannaatibc** [binance/binance-connector-node#130]
### Issue subject
I'm using @binance/connector for binance spot trading(I'm using testnet URL wss://testnet.binance.vision). I need to know the status of an order that I've placed. Initially for few minutes I was able receive the messages when trade happens. After that there are no messages from socket connection. But for every 10 seconds I'm sending PING messages and I'm receiving PONG messages. But when I place an order there are no messages in return. For now I can only able see the status of an order by making HTTP request to  https://testnet.binance.vision/api/v3/order

### Expected behaviour
I need binance websocket connection to be still. Not to be disconnected.

### Actual behaviour
Binance websocket connection is disconnecting after few minutes.

### Steps to reproduce
1. Create instance by const binanceClient = new Spot('', '', { wsURL: 'wss://testnet.binance.vision' })
2. Place SPOT order in any symbol.
const callbacks = {
    open: () => {
        this.binanceClient.logger.log('open')
    },
    close: () => {
        this.binanceClient.logger.log('closed')
    },
    message: res => {
        let parsedRes = JSON.parse(res)
        console.log(parsedRes); // Only for few minutes I can able to receive "res" param. After that it is not logging anything
    }
}
const wsRef = binanceClient.userData(listenKey, callbacks)

Only for few minutes I can able to receive "res" param. After that it is not logging anything

### Environment
* Version of @binance/connector - 2.0.0-rc.4
* Node version - v14.15.0
* Operating system - Linux

**Comment by 2pd** [comment]
please upgrade to the latest version and try again.

Please make sure you constantly placing orders for monitoring on testnet.
