### ISSUE TITLE
现货请求深度，错误。以前可以用，现在突然报错

### ISSUE THREAD

**Issue by Osub** [binance/binance-connector-node#131]
'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n' +
      '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">\n' +
      '<TITLE>ERROR: The request could not be satisfied</TITLE>\n' +
      '</HEAD><BODY>\n' +
      '<H1>400 ERROR</H1>\n' +
      '<H2>The request could not be satisfied.</H2>\n' +
      '<HR noshade size="1px">\n' +
      'Bad request.\n' +
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n" +
      '<BR clear="all">\n' +
      'If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n' +
      '<BR clear="all">\n' +
      '<HR noshade size="1px">\n' +
      '<PRE>\n' +
      'Generated by cloudfront (CloudFront)\n' +
      'Request ID: DDc228ZESXaTSMIZlcg-8x6_ivhAze3J1dtwbbVRMTICaavdbPBpLw==\n' +
      '</PRE>\n' +
      '<ADDRESS>\n' +
      '</ADDRESS>\n' +
      '</BODY></HTML>'

**Comment by 2pd** [comment]
看起来是请求发送的太多，被拦截了。 可以过一会试试。
