### ISSUE TITLE
TypeError: symbol.toUpperCase is not a function at Spot.allOrders

### ISSUE THREAD

**Issue by helderabreu** [binance/binance-connector-node#139]
I have a small NestJS application where I'm using `binance-connector`, but I have an issue when calling:
`client.allOrders({ symbol: 'BTCUSDT', timestamp: Date.now() })`

I'm getting the following error:
`TypeError: symbol.toUpperCase is not a function at Spot.allOrders (.../node_modules/@binance/connector/src/modules/restful/trade.js:249:24)`.

I'm running the `"@binance/connector": "^3.0.0-rc.2"` with `node v18.16.0` on Mac OS 13.4.

**Comment by teshtek** [comment]
Did you solve? Same error here

**Comment by Adi9378** [comment]
Hello, 
Sorry if i make a mistake on my answer.

isn't it a problem with your params ? 

I'm using the v2 so maybe it's different but i use it like this:

const { data } = await this.binance.allOrders(symbol, { limit, timestamp: Date.now() });

symbol is as first param, and the option object as second param

**Comment by OceanU** [comment]
> client.allOrders({ symbol: 'BTCUSDT', timestamp: Date.now() })

Hello !
Use it like this : 
`client.allOrders(symbol)`

**Comment by 2pd** [comment]
symbol is a mandatory parameter,  should you should provide it as first parameter. please check this example file of calling the method:

https://github.com/binance/binance-connector-node/blob/master/examples/spot/trade/allOrders.js
