### ISSUE TITLE
UNABLE TO MAKE ANY REQUEST

### ISSUE THREAD

**Issue by Dayo-Adewuyi** [binance/binance-connector-node#148]
### UNABLE TO MAKE ANY REQUEST
I am unable to make any request with the connector, I get a 400 Bad request error for the attached function

<img width="436" alt="Screenshot 2023-12-08 200651" src="https://github.com/binance/binance-connector-node/assets/92578713/c9a724ac-0923-4988-817d-53c2fbb2834d">

**Comment by 2pd** [comment]
what is the error message? 400 error indicates that it's client side error.

Thanks

**Comment by aisling-2** [comment]
@Dayo-Adewuyi We're closing this Issue due to lack of response. If there's further comments, you can re-open. :)
