### ISSUE TITLE
Error Making requests

### ISSUE THREAD

**Issue by Dayo-Adewuyi** [binance/binance-connector-node#149]
I keep getting this error even though I have whitelisted My IP and use the appropriate key.

<img width="429" alt="image" src="https://github.com/binance/binance-connector-node/assets/92578713/0e1fc8aa-9cd7-4ade-aa4d-0e96177ae980">

**Comment by 2pd** [comment]
The error is not related to this library, please refer to this topic for more details:

https://dev.binance.vision/t/why-do-i-see-this-error-invalid-api-key-ip-or-permissions-for-action/93
