### ISSUE TITLE
feat: Update OCO order endpoint to use /api/v3/orderList/oco

### ISSUE THREAD

**Issue by dizao** [binance/binance-connector-node#158]
**Issue subject**
Library is using the deprecated OCO order API endpoint

**Expected behaviour**
The library should use the new API endpoint for OCO orders.

**Actual behaviour**
The library is currently using the deprecated POST /api/v3/order/oco endpoint, which should be replaced with POST /api/v3/orderList.

**Steps to reproduce**
Use the library to create an OCO order.
Observe that it uses the deprecated POST /api/v3/order/oco endpoint.
The order creation should fail or result in a warning about the deprecated endpoint.

**Comment by alplabin** [comment]
It has been updated in the latest release: https://github.com/binance/binance-connector-node/releases/tag/v3.4.1
