### ISSUE TITLE
Connect

### ISSUE THREAD

**Issue by Joj501** [binance/binance-connector-node#178]

**Comment by Joj501** [comment]
How I connect Trustwallet with Binance

**Comment by alplabin** [comment]
Please contact customer support regarding this issue.

**Comment by Dappsnode** [comment]
@Joj501 Are you able to get it?

**Comment by Joj501** [comment]
Yes please conecct

**Comment by Joj501** [comment]
Yes connect

**Comment by Dappsnode** [comment]
@Joj501 Okay
