### ISSUE TITLE
spot.renewListenKey(listenKey) give error 400

### ISSUE THREAD

**Issue by emmtte** [binance/binance-connector-node#41]
Sometimes with :

`spot.renewListenKey(listenKey)`

have this error :
```
Error: Request failed with status code 400
    at createError (.../node_modules/axios/lib/core/createError.js:16:15)
    at settle (.../node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (.../node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (node:events:391:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
```

I call `spot.renewListenKey(listenKey)` every 30 minutes and when it's happend it's impossible to stop this error.
I need to restart the script

How to know more about this error with` catch`?

**Comment by ishuen** [comment]
Hi. Could you also share the error message? Usually when this endpoint returns 400, it has an error message attached, e.g. "Parameter 'listenKey' was empty.", "This listenKey does not exist."

**Comment by emmtte** [comment]
Hi,
Question ? How to find this error message because with that line :
`spot.renewListenKey(listenKey)` it's only show the error send above

**Comment by ishuen** [comment]
Please refer to `Getting Started > Error` section ( https://binance.github.io/binance-connector-node/gettingStarted.html ). Error response data is the part including the error message.
If you are not clear about how to get the error content, please also refer to the `catch` part of this example file: https://github.com/binance/binance-connector-node/blob/master/examples/spot/stream/renewListenKey.js

**Comment by emmtte** [comment]
Hi, thanks for your help.
After a while or after a network error have this error
`data: { code: -1125, msg: 'This listenKey does not exist.' }`

**Comment by ishuen** [comment]
Please check if the listenKey you sent to renew was the same as what you got from POST request.

**Comment by ishuen** [comment]
Close this issue as there is no further discussion.
