### ISSUE TITLE
Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by chahakshah111** [binance/binance-connector-node#64]
I'm getting Timestamp for this request was 1000ms ahead of the server's time. error while creating new order.
await client.newOrder("BNBUSDT", "BUY", "MARKET", {
      quantity: 100,
      timeInForce: "GTC",
      recvWindow: 20000,
    });
How can I solve this error?

**Comment by 2pd** [comment]
You need to sync your local time.
