### ISSUE TITLE
error console is not a constructor in utils

### ISSUE THREAD

**Issue by nageshnel** [binance/binance-connector-node#65]
any solution would be welcome.

#error
Uncaught TypeError: Console is not a constructor
  <anonymous> webpack: ./node_modules/@binance/connector/src/helpers/utils.js?:65

#webpack config
 resolve :fallback:{
            'crypto':require.resolve('crypto-browserify'),
             'console':require.resolve('console-browserify'),
         }

console-browserify does not support creating new Console instances and does not support the Inspector-only methods.

### Environment
 "@binance/connector": "^1.5.0",
 "react": "^17.0.2",
  "react-dom": "^17.0.2",
  "react-scripts": "^5.0.0"
"webpack": "^5.68.0",
node:16.14.0
os:windos 10.

**Comment by 2pd** [comment]
we didn't test how well this running in web brower since it's built for Nodejs. However, you may have a try to provide your owner logger.
https://github.com/binance/binance-connector-node/blob/master/src/APIBase.js#L11

**Comment by GigiSan** [comment]
Same problem arises when used in NuxtJS.
I'm trying to develop a bridge app which would use the connector as a M2M channel.

First it will raise an error on `require('console')` prompting you to `npm install console --save`
then if you install `console` the error above pops up.

**Comment by aisling11** [comment]
Hi @GigiSan, have you tried @2pd's suggestion? There's option to use user's own defined logger (some popular logger packages might include `winston` or `pino`) to skip the default logger used in the connector.

**Comment by nageshnel** [comment]
Hi,
yes I tried by passing new console object, but same error I got ,no
solution.

**Comment by aisling11** [comment]
Sorry to hear that, unfortunately we don’t think we’ll explore further on this error as browser testing is out of our scope for now and since a custom logger is accepted, this package doesn’t block a possible workaround if found by someone in the meantime.
