### ISSUE TITLE
Implementing binance connector to my react app

### ISSUE THREAD

**Issue by JakubKlimasWTT** [binance/binance-connector-node#68]
Hello,
I want to get information about crypto from my wallet api. But when I use:
const { Spot } = require('@binance/connector')

const apiKey = ''
const apiSecret = ''
const client = new Spot(apiKey, apiSecret)

// Get account information
client.account().then(response => client.logger.log(response.data))
I got the following errors in console. Can someone help me solve this problem?
![3426b7ee2e6f4ebda2c75adc364c7e88da363a8b_2_1035x646](https://user-images.githubusercontent.com/94619079/154805015-a8c89179-0801-4925-9e98-5f1f971a531f.png)
in console. Can someone help me solve this problem?

**Comment by 2pd** [comment]
> Sounds like you're trying to use Node module in browser, which is not possible. Fetch your account information on the backend part of the app and return response to the client / front end part.
> 
> I assume you want to SWR it or store the response in database as you don't want to hit that API so often.

Yes, Binance API secret is required for account/trade endpoints, you shouldn't export it to browser.
