### ISSUE TITLE
Add C2C individual order details

### ISSUE THREAD

**Issue by saurabhburade** [binance/binance-connector-node#73]
### Expected behaviour
Get C2C order detail.
It is expected to get the C2C individual order details for balance sheets.

**Comment by saurabhburade** [comment]
It is available on the Binance web app using the following API
`https://c2c.binance.com/bapi/c2c/v2/private/c2c/order-match/order-detail`

**Comment by 2pd** [comment]
Thank you for your feedback and hope this will be helpful.
