### ISSUE TITLE
Removed from NPM because of malicious code

### ISSUE THREAD

**Issue by antonio0** [binance/binance-connector-node#76]
From https://www.npmjs.com/package/@binance/connector :

> Security holding package
> This package contained malicious code and was removed from the registry by the npm security team. A placeholder was published to ensure users are not affected in the future.
> 
> Please refer to [www.npmjs.com/advisories?search=%40binance%2Fconnector](http://www.npmjs.com/advisories?search=%40binance%2Fconnector) for more information.

Reading "malicious code" about the company's official package isn't a great vote of confidence about any code/sdk in Binance org

**Comment by davscro** [comment]
I am wondering what malicious code? 🤔  I can not find and further explains at http://www.npmjs.com/advisories?search=%40binance%2Fconnector

**Comment by Mo-Sheikh** [comment]
> I am wondering what malicious code? 🤔 I can not find and further explains at http://www.npmjs.com/advisories?search=%40binance%2Fconnector.
> 
> Until is resolved, qfix is to put in package json reference to this repo `"@binance/connector": "git+https://github.com/binance/binance-connector-node.git",`

Wondering what the malicious code is too. Quite concerned. I rely on this library heavily.

**Comment by Mo-Sheikh** [comment]
Wondering what the malicious code is too. Quite concerned. I rely on this library heavily.

**Comment by 2pd** [comment]
We are investigating this issue. 
This library is open-sourced from the first version, everyone can review and see the whole source code.

The library only has 2 dependencies:
- "axios": "^0.21.4",
- "ws": "^7.5.0"

and a few for development.

Any updates we have will be provided.

**Comment by 2pd** [comment]
While waiting for feedback from NPM, we are not able to find anywhere that can give evidence of "malicious code" in this library.

- No vulnerability advisory from https://github.com/advisories?query=binance related to this library.
- We did some research, not able to target this library in the malicious npm package list from recent reports e.g:
  - https://jfrog.com/blog/large-scale-npm-attack-targets-azure-developers-with-malicious-packages/
  - https://jfrog.com/blog/malware-civil-war-malicious-npm-packages-targeting-malware-authors/

Please review the code and install by 

```json
"@binance/connector": "git+https://github.com/binance/binance-connector-node.git"
```

or 

```shell
npm install "@binance/connector" git+https://github.com/binance/binance-connector-node.git
```

**Comment by movy** [comment]
receiving this error when trying to install:

```
npm ERR! code EINTEGRITY
npm ERR! sha512-gI5Sl30tmhXsqkNvopFydP7ASc4c2cLfGNQrVKN3X90ADFWFsPEsotm/8JHSUJQKUSDTwowAHtcJPeyVhtKv0TQ== integrity checksum failed when using sha512: wanted sha512-gI5Sl30tmhXsqkNvopFydP7ASc4c2cLfGNQrVKN3X90ADFWFsPEsotm/8JHSUJQKUSDTwowAHtcJPeyVhtKv0TQ== but got sha512-gI5Sl30tmhXsqkNvopFydP7ASc4c2cLfGNQrVKN3X90ADFWFsPEsotm/8JHSUJQKTHbwowAHtcJPeyVhtKv0TQ==. (110735 bytes)
```

**Comment by 2pd** [comment]
what's your `node`, `npm` version?
and which OS are you in?

**Comment by 2pd** [comment]
maybe you can try to remove the `package-lock.json` file and install again.

**Comment by 2pd** [comment]
Close this ticket, please open a new one if seeing any issue. 
Thanks for your support.
