### ISSUE TITLE
Getting isolated margin info from accountSnapshot API

### ISSUE THREAD

**Issue by lingfei1999** [binance/binance-connector-node#78]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
Briefly describe the issue here.
I tried to use accountSnapshot API to get data however isolated margin info is not there.

### Expected behaviour
Describe what should happen.
isolated margin info should be included.

### Actual behaviour
Describe what happens instead. Please include the complete failure message.
Only cross margin and spot data are included.

### Steps to reproduce
Provide steps to let us know how we can reproduce this issue.
Just simply use accountSnapshot API to get the data.

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-node
* Node version
* Operating system

**Comment by 2pd** [comment]
isolated margin is not returned in this `GET /sapi/v1/accountSnapshot` endpoint.


Btw this is not an issue of the library,  for general API concern, please feel to open topic at dev.binance.vision.

Thanks
