### ISSUE TITLE
The lowest price sometimes is incorrect

### ISSUE THREAD

**Issue by vincentpham13** [binance/binance-connector-node#79]
### Issue subject
The lowest price sometimes is incorrect

### Expected behaviour
Describe what should happen.
it should be correct

### Actual behaviour
a strange lowest price
<img width="161" alt="image" src="https://user-images.githubusercontent.com/63580042/165422623-ac7255f7-15b8-4c00-a95d-2de48fd24904.png">
 
rendered chart
<img width="706" alt="image" src="https://user-images.githubusercontent.com/63580042/165423246-26873d50-d583-4ec0-9f72-143a4f734f9c.png">

### Steps to reproduce
spot.klines('BTCUSDT', '30m', { limit: 10 });

### Environment
* Version of binance-connector-node: 1.8.1
* Node version: v14.19.0
* Operating system: macOS

**Comment by 2pd** [comment]
Sorry I can't reproduce.

```javascript
client.klines('BNBUSDT', '30m', { limit: 1, startTime: 1651014000000 })
  .then(response => console.log(response.data))
  .catch(error => console.log(error))

```
and got

```json
[
  [
    1651014000000,
    '385.90000000',
    '386.40000000',
    '380.80000000',
    '382.30000000',
    '22584.20200000',
    1651015799999,
    '8647260.28060000',
    10502,
    '9394.52300000',
    '3598062.32040000',
    '0'
  ]
]

```
