### ISSUE TITLE
Bed withdraw example response

### ISSUE THREAD

**Issue by gfijrb** [binance/binance-connector-node#82]
https://github.com/binance/binance-connector-node/blob/e3cdbd7725f631342d14a800c4ff6f269ff324ac/examples/spot/wallet/withdraw.js#L7

This example returns error, how to fix it?

code: -1002,
msg: 'You are not authorized to execute this request.

**Comment by tantialex** [comment]
The API-KEY you are using may have missing WITHDRAWAL permissions.

**Comment by gfijrb** [comment]
> 

many thanks!!!
