### ISSUE TITLE
Error when trying to get more than one symbol on tickers API

### ISSUE THREAD

**Issue by vinicius91carvalho** [binance/binance-connector-node#85]
### Issue subject
Error when trying to get more than one symbol on tickers API

### Expected behavior
It needs to return an array as the docs say here: [24hr-ticker-price-change-statistics](https://binance-docs.github.io/apidocs/spot/en/#24hr-ticker-price-change-statistics)

### Actual behavior
The API answer with the data below:
```
data: {
  code: -1100,
  msg: "Illegal characters found in parameter 'symbol'; legal range is '^[A-Z0-9-_.]{1,20}$'."
}
```

### Steps to reproduce

```
const symbols = '["BNBBTC","BTCUSDT"]'
let response
try {
    response = await this.client.ticker24hr(symbols)
} catch (error) {
    console.error(error)
    return []
}
```

The API will be called on this way: **/api/v3/ticker/24hr?symbol=%5B%22BNBBTC%22%2C%22BTCUSDT%22%5D**

Because internally there is a call to the encodeURIComponent. The example on Binance Docs is **%5B%22BTCUSDT%22,%22BNBUSDT%22%5D**, which theoretically is impossible. The regex on the error says that only alphanumeric data can be sent. I'm a little confused about it.

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-node
* Node version: v14.19.0
* Operating system: Mac OS Monterey

**Comment by tantialex** [comment]
Issue should be resolved with #86 

`await this.client.ticker24hr('', symbols)`
