### ISSUE TITLE
Cant install version of 1.5.0

### ISSUE THREAD

**Issue by nipeharefa** [binance/binance-connector-node#87]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
I can't install spesific version for example v1.5.0
<img width="798" alt="image" src="https://user-images.githubusercontent.com/12620257/170819149-59a1ccc6-58bd-4adf-a902-0ee72bd16a03.png">. Can you republish it?

### Steps to reproduce
npm i "@binance/connector@1.5.0"

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-node: v1.5.0
* Node version: v14.17.5
* Operating system: BigSur

**Comment by nipeharefa** [comment]
Hi, @2pd I have a project a couple of months ago when starting the project the version of the connector is 1.5.0. So I need to ensure,no breaking changes if I want to upgrade to the latest version.

**Comment by 2pd** [comment]
Previously NPM removed the package by accident, and some of old versions are lost.
You can see some the changelogs in each version in from here https://github.com/binance/binance-connector-node/blob/master/CHANGELOG.md

we don't do breaking changes in feature version upgrading, however it's strongly recommended you review the change log and test them locally.
