### ISSUE TITLE
报错 Error: read ECONNRESET

### ISSUE THREAD

**Issue by KittenYang** [binance/binance-connector-node#88]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
Briefly describe the issue here.

### Expected behaviour
Describe what should happen.

### Actual behaviour
Describe what happens instead. Please include the complete failure message.

### Steps to reproduce
Provide steps to let us know how we can reproduce this issue.
download repo
yarn install
run tickerPrice.js
error:
```
<ref *1> Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read',
  config: {
    url: '/api/v3/ticker/price?symbol=BTCUSDT',
```

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-node  lastest
* Node version "node": ">=12.22.3",
* Operating system  mac os 12.4

**Comment by 2pd** [comment]
are you able to run curl to get server time?

curl -v "https://api.binance.com/api/v3/time"
