### ISSUE TITLE
npm critical - malware

### ISSUE THREAD

**Issue by admidelu** [binance/binance-connector-node#89]
Hello, why is it flagged as malware in npm? https://github.com/advisories/GHSA-9jc2-px24-4634

**Comment by 2pd** [comment]
Hi, we will investigate this.

**Comment by 2pd** [comment]
This report relate to https://www.npmjs.com/package/binance-connector-node, which is flagged as malware.
That is total a different package, not managed by us.
This package is released under "@binance" organization, so make sure you will install it via:

```
@binance/connector
```

**Comment by 2pd** [comment]
OK, we are investigating this.

Github reports:

```
Malware in @binance/connector - https://github.com/advisories/GHSA-9jc2-px24-4634
```
which indicate security concern from npm package: https://www.npmjs.com/package/@binance/connector

However we can't find any issue from npm side.


We will give update when it's available.

**Comment by 2pd** [comment]
https://github.com/advisories/GHSA-9jc2-px24-4634 is gone.

Recently github released a new advisor feature that flagged a few npm packages under @binance account.  Github team has removed those warnings from their side.

https://github.blog/2022-06-15-github-now-publishes-malware-advisories-in-the-github-advisory-database
