### ISSUE TITLE
Using A proxy

### ISSUE THREAD

**Issue by NeoHuncho** [binance/binance-connector-node#90]
I'm trying to parse a proxy to the client but it does not seem to work. Could you give the correct way of doing it? Thanks

**Comment by d11wtq** [comment]
This is listed in the README as one of the features:

> Customizable base URL, request timeout and HTTP proxy

**Comment by xoda** [comment]
Remove it from the documentation if it's not supported. It's definitely misleading.

**Comment by 2pd** [comment]
This is supported in latest version.

**Comment by robyle** [comment]
> This is supported in latest version.

excuse me , how to supported,can your easily show the proxies coding on .
