### ISSUE TITLE
Futures API Support

### ISSUE THREAD

**Issue by mrichtsfeld** [binance/binance-connector-node#91]
Hi, 

First, thanks for the great library. 

Second, I wanted to ask if there is a specific reason why the Futures API is not supported by this library?

Thanks for your help.

**Comment by 2pd** [comment]
We prefer to separate spot and futures into different packages,  users can choose the packages they wish to use.

**Comment by mrichtsfeld** [comment]
@2pd thank you for your reply. 

I did not find any node package for Binance Futures, only Python and Java. Did I miss something?

**Comment by 2pd** [comment]
Unfortunately it's still in the plan.

**Comment by mrichtsfeld** [comment]
Got it, thanks for the information.

**Comment by mrichtsfeld** [comment]
Hi, just wanted to check if there is already an update on the Futures library release date?

**Comment by 2pd** [comment]
Sorry that still no ETA.

**Comment by ash-hashtag** [comment]
update?

**Comment by 2pd** [comment]
Unfortunately we don't have plan for it yet.

**Comment by 3anz** [comment]
got this package installed to manage my futures wallet and then got disappointed 😂 Hope you guys provide the support soon ❤️

**Comment by ee-kon** [comment]
hi, is there an update on the feature?

**Comment by 2pd** [comment]
Thanks for waiting, we have released a new connector for futures only at https://github.com/binance/binance-futures-connector-node

It follow the same design of this spot one, simple and easy to read the code.
It is possible use them together in one project.  So it can be handy for different needs.
