### ISSUE TITLE
Data bug - BTC $100k

### ISSUE THREAD

**Issue by admidelu** [binance/binance-connector-node#95]
Hello, there seem to be bugs in the data - reporting BTC close price of $100,000 for some ticks:

case:
```
const test = await client.klines("BTCUSDT", "1m", {
		limit: 1,
		endTime: 1656201900000,
	});
```
	
response:
```
[
      1656201900000,
      '21499.19000000',
      '100000.00000000',
      '21477.62000000',
      '100000.00000000',
      '13.19828800',
      1656201959999,
      '315405.16449505',
      336,
      '9.85046700',
      '243448.77692294',
      '0'
 ]
```
The pricing has otherwise been consistent besides these few outliers
<img width="923" alt="outliers" src="https://user-images.githubusercontent.com/47508281/176442752-95d8f62d-dfea-4a6a-98f6-02208e44f267.png">

or am I missing something?

**Comment by 2pd** [comment]
that's data from testnet.

The base urls for both environments:
- testnet: https://testnet.binance.vision
- production: https://api.binance.com

**Comment by admidelu** [comment]
Ah thank you
