### ISSUE TITLE
Specifying a Connection/Request Timeout

### ISSUE THREAD

**Issue by d11wtq** [binance/binance-connector-node#98]
According to the README:

> Customizable base URL, request timeout and HTTP proxy

However I can't see how you'd provide a request timeout. It looks like no such option is passed through to axios.

Would be good to have something like:

```
new Spot(apiKey, apiSecret, {
  baseURL: 'https://testnet.binance.vision',
  requestTimeout: 5000,
})
```

I just had a momentary internet outage and when it came back online my bot was in a hung state as it somehow had sent a request and was expecting a response it would never receive.

**Comment by 2pd** [comment]
We will support it in future.

Thanks

**Comment by 2pd** [comment]
This is supported in latest version.
